name = "SymbolicManipulations"
uuid = "28ad4e8f-d0ac-45bd-8f68-259989dd4d5f"
authors = ["Luke Adams <luke@lukeclydeadams.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
DataStructures = "0.18"
Setfield = "0.7"
SymbolicUtils = "0.11, 0.12"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
